// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKkLee6YmTj9dRjJhnbrZ2o3Ovex9al4I',
    appId: '1:1045857258562:web:1a8d55084951c9b24371db',
    messagingSenderId: '1045857258562',
    projectId: 'final-exam-flutter-2120a',
    authDomain: 'final-exam-flutter-2120a.firebaseapp.com',
    storageBucket: 'final-exam-flutter-2120a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPz_eA-zFV9aCrSYgB-wAiY1K-1HdIWzY',
    appId: '1:1045857258562:android:bdd895ae0de7b2ba4371db',
    messagingSenderId: '1045857258562',
    projectId: 'final-exam-flutter-2120a',
    storageBucket: 'final-exam-flutter-2120a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkKHtct8bPh13A98ulFHRdueWw7Ij10Zk',
    appId: '1:1045857258562:ios:db6dcc12b7e8cc584371db',
    messagingSenderId: '1045857258562',
    projectId: 'final-exam-flutter-2120a',
    storageBucket: 'final-exam-flutter-2120a.appspot.com',
    iosBundleId: 'com.example.finalExamFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkKHtct8bPh13A98ulFHRdueWw7Ij10Zk',
    appId: '1:1045857258562:ios:db6dcc12b7e8cc584371db',
    messagingSenderId: '1045857258562',
    projectId: 'final-exam-flutter-2120a',
    storageBucket: 'final-exam-flutter-2120a.appspot.com',
    iosBundleId: 'com.example.finalExamFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKkLee6YmTj9dRjJhnbrZ2o3Ovex9al4I',
    appId: '1:1045857258562:web:64482b18646dd7604371db',
    messagingSenderId: '1045857258562',
    projectId: 'final-exam-flutter-2120a',
    authDomain: 'final-exam-flutter-2120a.firebaseapp.com',
    storageBucket: 'final-exam-flutter-2120a.appspot.com',
  );
}
